project:
  type: book
  output-dir: content

book:
  title: "MPac AI Playbook"
  author: "Rob Braun & Witek ten Hove"
  date: "4/11/2024"
  navbar:
    logo: logo.png
    search: true
  chapters:
    - index.qmd
    - intro.qmd
    - foundation.qmd
    - ecosystem.qmd
    - implementation.qmd
    - scaling.qmd
    - aiculture.qmd
    - businesscases.qmd
    - resources.qmd
    - next.qmd
    - appendices.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-after-body: scripts.js
    logo: logo.png
  pdf:
    documentclass: scrreprt

editor: visual

